#!/usr/bin/env bash
# Tests install.sh in a throwaway HOME: it may only remove or replace what
# provably belongs to ODrive. Stubs stand in for omarchy/omarchy-shell, so the
# real shell and bar are never touched.
#
#   tests/test_install.sh            test this checkout's install.sh
#   tests/test_install.sh <checkout> test another checkout's install.sh
#                                    (e.g. a git worktree of an older commit)
set -u

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO="$(cd "${1:-$HERE}" && pwd)"
S="$(mktemp -d)"
trap 'rm -rf -- "${S:?}"' EXIT
PASS=0; FAIL=0; SKIP=0

check() { if eval "$2"; then PASS=$((PASS+1)); echo "  ok   $1"; else FAIL=$((FAIL+1)); echo "  FAIL $1"; fi; }
skip() { SKIP=$((SKIP+1)); echo "  skip $1"; }

fresh() {
  export HOME="$S/home"; rm -rf -- "${S:?}/home" "${S:?}/stubs" "${S:?}/other"
  mkdir -p "$HOME" "$S/stubs" "$S/other"
  printf '#!/bin/bash\necho "omarchy $*" >> %s/calls.log\n[[ "$1 $2" == "plugin list" ]] && echo "[]"\nexit 0\n' "$S" > "$S/stubs/omarchy"
  printf '#!/bin/bash\necho "omarchy-shell $*" >> %s/calls.log\n' "$S" > "$S/stubs/omarchy-shell"
  chmod +x "$S/stubs/"*; : > "$S/calls.log"
  export PATH="$S/stubs:/usr/bin:/bin"
  P="$HOME/.config/omarchy/plugins/ttt.odrive"; B="$HOME/.local/bin/odrive"; D="$HOME/.local/share/applications"
}
run() { bash "$REPO/install.sh" --no-enable "$@" > "$S/out.log" 2>&1; echo $?; }
# A copy exactly as an older (marker-less) installer left it, from committed content
legacy_copy() { mkdir -p "$P"; git -C "$HERE" archive HEAD manifest.json ui bin lib assets | tar -x -C "$P"; }
HAVE_GIT=false; git -C "$HERE" rev-parse --verify -q HEAD >/dev/null 2>&1 && HAVE_GIT=true
LEGACY_DESKTOP=""
if git -C "$HERE" show 0e4b0f4:assets/odrive.desktop > "$S/legacy.desktop" 2>/dev/null; then LEGACY_DESKTOP="$S/legacy.desktop"; fi

echo "testing $REPO/install.sh"

echo "1. fresh install writes a hash-recording marker"
fresh; rc=$(run)
check "installed" '[[ $rc == 0 && -f $P/manifest.json ]]'
check "marker records every file" '[[ $(grep -cE "^[0-9a-f]{64}  " $P/.odrive-install) == $(cd $P && find . -type f ! -name .odrive-install | wc -l) ]]'
check "no __pycache__ or tests shipped" '[[ -z $(find $P -name __pycache__) && ! -e $P/tests ]]'
check "CLI linked" '[[ $(readlink $B) == $P/bin/odrive ]]'
check "no staging leftovers" '[[ -z $(ls -A $HOME/.config/omarchy/plugins | grep "^\.") ]]'

echo "2. reinstall over an unchanged copy"
rc=$(run); check "replaced" '[[ $rc == 0 && -f $P/.odrive-install ]]'

echo "3. files added after install are never deleted"
fresh; run >/dev/null; echo "// my widget" > "$P/ui/MyWidget.qml"; rc=$(run)
check "reinstall refused, file kept" '[[ $rc == 1 && -f $P/ui/MyWidget.qml ]]'
check "lists the added file" 'grep -q "added: ui/MyWidget.qml" $S/out.log'
rc=$(run --uninstall)
check "uninstall refused, file kept, not disabled" '[[ $rc == 1 && -f $P/ui/MyWidget.qml ]] && ! grep -q "plugin disable" $S/calls.log'

echo "4. local edits are never deleted"
fresh; run >/dev/null; echo "// tweak" >> "$P/ui/Panel.qml"; rc=$(run)
check "reinstall refused, edit kept" '[[ $rc == 1 && $(tail -1 $P/ui/Panel.qml) == "// tweak" ]]'
check "lists the changed file" 'grep -q "changed: ui/Panel.qml" $S/out.log'
rc=$(run --uninstall); check "uninstall refused, edit kept" '[[ $rc == 1 && -f $P/ui/Panel.qml ]]'

echo "5. directories added after install are never deleted"
fresh; run >/dev/null; mkdir "$P/ui/Empty"; rc=$(run)
check "empty dir: reinstall refused, kept" '[[ $rc == 1 && -d $P/ui/Empty ]] && grep -q "added: ui/Empty/" $S/out.log'
rc=$(run --uninstall); check "empty dir: uninstall refused, kept" '[[ $rc == 1 && -d $P/ui/Empty ]]'
fresh; run >/dev/null; mkdir -p "$P/lib/odrive/mine/deeper/still"; rc=$(run)
check "nested empty dirs: refused, kept" '[[ $rc == 1 && -d $P/lib/odrive/mine/deeper/still ]]'

echo "6. special entries are flagged without being read"
fresh; run >/dev/null; ln -s "$S/other" "$P/ui/linked"; rc=$(run)
check "symlink: refused, kept" '[[ $rc == 1 && -L $P/ui/linked ]]'
fresh; run >/dev/null; mkfifo "$P/ui/pipe"
timeout 20 bash "$REPO/install.sh" --no-enable > "$S/out.log" 2>&1; rc=$?
check "FIFO: refused without hanging, kept" '[[ $rc == 1 && -p $P/ui/pipe ]]'

echo "7. only regenerated bytecode is ignored"
fresh; run >/dev/null; mkdir -p "$P/lib/odrive/__pycache__"; echo x > "$P/lib/odrive/__pycache__/cli.cpython-314.pyc"; rm "$P/assets/icon.svg"; rc=$(run)
check "bytecode + missing file: still replaced" '[[ $rc == 0 && -f $P/assets/icon.svg ]]'
fresh; run >/dev/null; "$P/bin/odrive" --preview status >/dev/null 2>&1; rc=$(run --uninstall)
check "uninstall after the CLI really ran" '[[ $rc == 0 && ! -e $P ]]'
fresh; run >/dev/null; mkdir -p "$P/lib/odrive/__pycache__"; echo keep > "$P/lib/odrive/__pycache__/notes.txt"; rc=$(run)
check "non-.pyc in __pycache__: refused, kept" '[[ $rc == 1 && -f $P/lib/odrive/__pycache__/notes.txt ]]'
fresh; run >/dev/null; echo x > "$P/ui/cache.pyc"; rc=$(run --uninstall)
check ".pyc outside __pycache__: refused, kept" '[[ $rc == 1 && -f $P/ui/cache.pyc ]]'

echo "8. copies from older installers (no hashes) are checked against git history"
if [[ $HAVE_GIT == true ]]; then
  fresh; legacy_copy; rc=$(run)
  check "pristine: replaced" '[[ $rc == 0 && -f $P/.odrive-install ]]'
  fresh; legacy_copy; echo "// mine" >> "$P/ui/Service.qml"; rc=$(run)
  check "edited: refused, kept" '[[ $rc == 1 && $(tail -1 $P/ui/Service.qml) == "// mine" ]]'
  fresh; legacy_copy; mkdir "$P/assets/extra"; rc=$(run --uninstall)
  check "added dir: uninstall refused, kept" '[[ $rc == 1 && -d $P/assets/extra ]]'
  fresh; legacy_copy; printf 'Installed by ODrive install.sh from /somewhere\n' > "$P/.odrive-install"; rc=$(run)
  check "text-only marker verified via git" '[[ $rc == 0 && $(grep -cE "^[0-9a-f]{64}  " $P/.odrive-install) -gt 0 ]]'
  fresh; legacy_copy; mkdir -p "$S/other/nogit"; cp -r "$REPO"/{manifest.json,ui,bin,lib,assets,install.sh} "$S/other/nogit/"
  bash "$S/other/nogit/install.sh" --no-enable > "$S/out.log" 2>&1; rc=$?
  check "no git history to check: refused" '[[ $rc == 1 && -f $P/manifest.json ]] && grep -q "did not record" $S/out.log'
else
  skip "no git history in $HERE"
fi

echo "9. things that were never ODrive's"
fresh; mkdir -p "$P"; echo '{"id":"someone.else"}' > "$P/manifest.json"; rc=$(run)
check "unrelated plugin refused" '[[ $rc == 1 && -f $P/manifest.json ]]'
fresh; mkdir -p "$P"; cp -r "$REPO"/{manifest.json,ui,bin,lib,assets} "$P/"; mkdir "$P/.git"; rc=$(run)
check "git checkout refused" '[[ $rc == 1 && -d $P/.git ]] && grep -q "git checkout" $S/out.log'
fresh; mkdir -p "$(dirname "$P")"; echo keep > "$S/other/data"; ln -s "$S/other" "$P"; rc=$(run)
check "symlink elsewhere refused" '[[ $rc == 1 && -f $S/other/data ]]'
fresh; cp -r "$REPO" "$S/other/checkout"; mkdir -p "$(dirname "$P")"; ln -s "$S/other/checkout" "$P"; rc=$(run --uninstall)
check "--link: only the link removed" '[[ $rc == 0 && ! -e $P && -f $S/other/checkout/install.sh ]]'
fresh; rc=$(run --link); check "--link install" '[[ $rc == 0 && -L $P && $(readlink $P) == $REPO ]]'
fresh; mkdir -p "$(dirname "$P")"; cp -r "$REPO" "$P"; echo x > "$P/local-edit.txt"
bash "$P/install.sh" --no-enable > "$S/out.log" 2>&1; rc=$?
check "run from inside the plugin folder: nothing deleted" '[[ $rc == 0 && -f $P/local-edit.txt && -f $P/install.sh ]]'
fresh; mkdir -p "$(dirname "$B")"; printf '#!/bin/sh\necho other\n' > "$B"; rc=$(run)
check "unrelated ~/.local/bin/odrive kept" '[[ $rc == 0 && ! -L $B ]] && grep -q "not ODrive" $S/out.log'

echo "10. desktop entries"
fresh; mkdir -p "$D"; printf '[Desktop Entry]\nName=Mine\nExec=odrive status\n' > "$D/odrive.desktop"; run >/dev/null; run --uninstall >/dev/null
check "user-made entry running odrive kept" '[[ -f $D/odrive.desktop ]]'
if [[ -n $LEGACY_DESKTOP ]]; then
  fresh; mkdir -p "$D"; cp "$LEGACY_DESKTOP" "$D/odrive.desktop"; run >/dev/null
  check "exact legacy entry removed" '[[ ! -e $D/odrive.desktop ]]'
  fresh; mkdir -p "$D"; sed 's/^Terminal=false/Terminal=true/' "$LEGACY_DESKTOP" > "$D/odrive.desktop"; run >/dev/null
  check "edited legacy entry kept" '[[ -f $D/odrive.desktop ]]'
else
  skip "legacy desktop entry not in git history"
fi

echo "11. clean uninstall"
fresh; run >/dev/null; rc=$(run --uninstall)
check "copy and CLI link removed, plugin disabled" '[[ $rc == 0 && ! -e $P && ! -L $B ]] && grep -q "plugin disable" $S/calls.log'

echo; echo "passed $PASS, failed $FAIL, skipped $SKIP"
[[ $FAIL == 0 ]]
